dist: bionic
sudo: required
language: c

os: linux

addons:
  apt:
    packages:
      - valgrind
      - lcov

before_install:
  - sudo apt update
  - sudo apt install valgrind
  - sudo apt install clang-format
  - sudo apt install lcov
  - sudo apt install libstdc++6
  - sudo apt install cmake

compiler:
  - gcc
  - clang

install:
  - source ci/install-linux.sh

script:
  - cmake .
  - make || travis_terminate 1
  - valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all --leak-resolution=med  --track-origins=yes ./iz1_task || travis_terminate 1
#  - make tests

after_success:
  - lcov --capture --directory . --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info