dist: bionic
sudo: required
language: c

os: linux

addons:
  apt:
    packages:
      - valgrind
      - lcov

before_install:
  - sudo apt update
  - sudo apt install valgrind
  - sudo apt install clang-format
  - sudo apt install lcov
  - sudo apt install libstdc++6
  - sudo apt install cmake

compiler:
  - gcc
  - clang

install:
  - source ci/install-linux.sh

script:
  - mkdir build
  - cd build
  - cmake ..
  - cd /home/travis/build/vr009/TP_c_cpp/build
  - make
#  - make tests

after_success:
  - lcov --capture --directory . --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info