dist: bionic
sudo: required
language: c

os: linux

addons:
  apt:
    packages:
      - valgrind
      - lcov

before_install:
  - sudo apt update
  - sudo apt install valgrind
  - sudo apt install clang-format
  - sudo apt install lcov
  - sudo apt install libstdc++6
  - sudo apt install cmake

compiler:
  - gcc

#env:
#  global:
#    - CODECOV_TOKEN='d3c18c1c-f6c0-47e8-855c-83e8d14219c1'

install:
  - sudo apt-get update
  - sudo apt-get install valgrind
  - sudo apt-get install clang-format
  - sudo apt-get install lcov
  - sudo apt-get install libstdc++6
  - sudo apt-get install cmake
  - sudo apt-get install cppcheck
  # Google tests
  - sudo apt-get install libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake .
  - sudo make
  - sudo cp *.a /usr/lib
  - cd -

script:
  - cmake .
  - make || travis_terminate 1
  - cppcheck *.c --enable=all --verbose
  - valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all --leak-resolution=med  --track-origins=yes ./T2 ./autotest.txt || travis_terminate 1
  - ./tests_simple
  - ./tests_parallel
  - ./tests_file_worker
#  - make tests

after_success:
  - lcov --capture --directory . --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info